-- Milestone 3: seed the public exercise library (~60 common strength exercises).
-- Public library rows (is_custom = false) bypass client RLS insert restrictions
-- because this runs via the SQL Editor as the table owner.

insert into public.exercises (name, category, primary_muscle, equipment, instructions) values
  ('Barbell Back Squat', 'legs', 'quadriceps', 'barbell', 'Bar on upper back, feet shoulder-width, squat until hips below knees, drive up through mid-foot.'),
  ('Barbell Front Squat', 'legs', 'quadriceps', 'barbell', 'Bar racked on front delts, elbows high, squat while keeping torso upright.'),
  ('Barbell Deadlift', 'pull', 'hamstrings', 'barbell', 'Hinge at hips, flat back, bar close to shins, drive through the floor to stand.'),
  ('Romanian Deadlift', 'pull', 'hamstrings', 'barbell', 'Slight knee bend, hinge at hips lowering bar along legs, feel hamstring stretch, return to standing.'),
  ('Barbell Bench Press', 'push', 'chest', 'barbell', 'Lie on bench, lower bar to mid-chest, press to lockout with shoulder blades retracted.'),
  ('Incline Barbell Bench Press', 'push', 'chest', 'barbell', 'Bench at 30-45 degrees, lower bar to upper chest, press to lockout.'),
  ('Overhead Press', 'push', 'shoulders', 'barbell', 'Bar at shoulder height, press overhead to lockout without leaning back excessively.'),
  ('Barbell Row', 'pull', 'back', 'barbell', 'Hinge forward, pull bar to lower ribs, squeeze shoulder blades, lower under control.'),
  ('Pendlay Row', 'pull', 'back', 'barbell', 'Torso parallel to floor, bar starts on the ground each rep, explosive pull to torso.'),
  ('Barbell Hip Thrust', 'legs', 'glutes', 'barbell', 'Upper back on bench, bar over hips, drive hips up to full extension, squeeze glutes.'),
  ('Barbell Lunge', 'legs', 'quadriceps', 'barbell', 'Bar on back, step forward into a lunge, drive through front heel to return.'),
  ('Barbell Hip Thrust Belt', 'legs', 'glutes', 'other', 'Belted hip thrust variation, drive hips up to full extension.'),
  ('Sumo Deadlift', 'pull', 'glutes', 'barbell', 'Wide stance, hands inside knees, hinge and drive through the floor to stand.'),
  ('Close-Grip Bench Press', 'push', 'triceps', 'barbell', 'Hands shoulder-width or closer, lower bar to chest, press focusing on triceps.'),
  ('Dumbbell Bench Press', 'push', 'chest', 'dumbbell', 'Press dumbbells from chest level to lockout, controlling the descent.'),
  ('Dumbbell Incline Press', 'push', 'chest', 'dumbbell', 'Incline bench, press dumbbells from shoulder level to lockout.'),
  ('Dumbbell Shoulder Press', 'push', 'shoulders', 'dumbbell', 'Press dumbbells from shoulder height to overhead lockout.'),
  ('Dumbbell Row', 'pull', 'back', 'dumbbell', 'One knee on bench, row dumbbell to hip, squeeze shoulder blade at top.'),
  ('Dumbbell Romanian Deadlift', 'pull', 'hamstrings', 'dumbbell', 'Hinge at hips lowering dumbbells along legs, return to standing.'),
  ('Dumbbell Goblet Squat', 'legs', 'quadriceps', 'dumbbell', 'Hold dumbbell at chest, squat down keeping torso upright, drive back up.'),
  ('Dumbbell Bulgarian Split Squat', 'legs', 'quadriceps', 'dumbbell', 'Rear foot elevated, lower into a lunge, drive through front heel.'),
  ('Dumbbell Lateral Raise', 'push', 'shoulders', 'dumbbell', 'Raise dumbbells out to the sides to shoulder height, lower under control.'),
  ('Dumbbell Rear Delt Fly', 'pull', 'shoulders', 'dumbbell', 'Hinge forward, raise dumbbells out to sides targeting rear delts.'),
  ('Dumbbell Bicep Curl', 'pull', 'biceps', 'dumbbell', 'Curl dumbbells to shoulders keeping elbows fixed, lower under control.'),
  ('Dumbbell Hammer Curl', 'pull', 'biceps', 'dumbbell', 'Curl dumbbells with neutral grip, elbows fixed at sides.'),
  ('Dumbbell Skull Crusher', 'push', 'triceps', 'dumbbell', 'Lying on bench, lower dumbbells to forehead, extend to lockout.'),
  ('Dumbbell Step-Up', 'legs', 'quadriceps', 'dumbbell', 'Step onto a box holding dumbbells, drive through the lead leg to stand.'),
  ('Dumbbell Farmer Carry', 'full_body', 'grip', 'dumbbell', 'Hold heavy dumbbells at sides, walk a set distance keeping posture tall.'),
  ('Pull-Up', 'pull', 'back', 'bodyweight', 'Hang from bar, pull chin over the bar, lower under control.'),
  ('Chin-Up', 'pull', 'biceps', 'bodyweight', 'Underhand grip, pull chin over the bar, lower under control.'),
  ('Push-Up', 'push', 'chest', 'bodyweight', 'Plank position, lower chest to floor, press back up keeping core tight.'),
  ('Dip', 'push', 'triceps', 'bodyweight', 'Support on parallel bars, lower until shoulders below elbows, press up.'),
  ('Bodyweight Squat', 'legs', 'quadriceps', 'bodyweight', 'Feet shoulder-width, squat down keeping chest up, drive back to standing.'),
  ('Walking Lunge', 'legs', 'quadriceps', 'bodyweight', 'Step forward into a lunge, alternate legs walking forward.'),
  ('Glute Bridge', 'legs', 'glutes', 'bodyweight', 'Lie on back, drive hips up squeezing glutes, lower under control.'),
  ('Plank', 'core', 'core', 'bodyweight', 'Hold a straight line from head to heels on forearms, brace core.'),
  ('Side Plank', 'core', 'obliques', 'bodyweight', 'Support on one forearm, hips lifted in a straight line, hold.'),
  ('Hanging Leg Raise', 'core', 'core', 'bodyweight', 'Hang from bar, raise legs to hip height or higher, lower under control.'),
  ('Sit-Up', 'core', 'core', 'bodyweight', 'Lie on back, curl torso up to knees, lower under control.'),
  ('Mountain Climber', 'cardio', 'core', 'bodyweight', 'Plank position, drive knees alternately toward chest at pace.'),
  ('Burpee', 'cardio', 'full_body', 'bodyweight', 'Squat, kick back to plank, push-up, jump feet in, jump up.'),
  ('Jumping Jack', 'cardio', 'full_body', 'bodyweight', 'Jump feet out while raising arms overhead, return to start.'),
  ('Bodyweight Calf Raise', 'legs', 'calves', 'bodyweight', 'Rise onto toes, pause, lower heels under control.'),
  ('Lat Pulldown', 'pull', 'back', 'cable', 'Pull bar down to upper chest, squeeze shoulder blades, return under control.'),
  ('Seated Cable Row', 'pull', 'back', 'cable', 'Pull handle to torso keeping back straight, squeeze shoulder blades.'),
  ('Cable Tricep Pushdown', 'push', 'triceps', 'cable', 'Elbows fixed at sides, extend forearms down to lockout.'),
  ('Cable Face Pull', 'pull', 'shoulders', 'cable', 'Pull rope to face height, elbows high, squeeze rear delts.'),
  ('Cable Woodchopper', 'core', 'obliques', 'cable', 'Rotate torso pulling cable diagonally across the body.'),
  ('Cable Chest Fly', 'push', 'chest', 'cable', 'Arms slightly bent, bring handles together in front of chest.'),
  ('Leg Press', 'legs', 'quadriceps', 'machine', 'Feet shoulder-width on platform, lower under control, press to near lockout.'),
  ('Leg Extension', 'legs', 'quadriceps', 'machine', 'Extend legs against pad to full extension, lower under control.'),
  ('Leg Curl', 'legs', 'hamstrings', 'machine', 'Curl pad toward glutes, lower under control.'),
  ('Chest Press Machine', 'push', 'chest', 'machine', 'Press handles forward to lockout, return under control.'),
  ('Shoulder Press Machine', 'push', 'shoulders', 'machine', 'Press handles overhead to lockout, return under control.'),
  ('Seated Row Machine', 'pull', 'back', 'machine', 'Pull handles to torso, squeeze shoulder blades, return under control.'),
  ('Calf Raise Machine', 'legs', 'calves', 'machine', 'Rise onto toes against resistance, pause, lower under control.'),
  ('Kettlebell Swing', 'full_body', 'glutes', 'kettlebell', 'Hinge at hips, swing kettlebell to chest height using hip drive.'),
  ('Kettlebell Goblet Squat', 'legs', 'quadriceps', 'kettlebell', 'Hold kettlebell at chest, squat down keeping torso upright.'),
  ('Kettlebell Turkish Get-Up', 'full_body', 'core', 'kettlebell', 'Complex ground-to-standing movement keeping kettlebell locked overhead.'),
  ('Band Pull-Apart', 'pull', 'shoulders', 'band', 'Hold band at shoulder height, pull apart squeezing shoulder blades.'),
  ('Band Face Pull', 'pull', 'shoulders', 'band', 'Pull band toward face, elbows high, squeeze rear delts.')
on conflict do nothing;
